#!/usr/bin/with-contenv bash
echo >&2 "starting sshd"
ssh-keygen -t ecdsa -b 256 -f $HOME/.ssh/id_ecdsa -N ""
cat $HOME/.ssh/id_ecdsa.pub >> $HOME/.ssh/authorized_keys
echo '------ ssh key ------'
cat $HOME/.ssh/id_ecdsa
echo '---------------------'
exec /usr/sbin/sshd -D -e 2>&1
